search_terms = [
    "san diego county employees",
    "san diego employees",
    "san diego employees retirement",
    "county of san diego deferred compensation program",
    "bos",
    "board of",
    "sd board of",
    "da",
    "cao",
    "apcd",
    "bpza",
    "perb",
    "lafco",
    "planning comm",
    "purchasing & contracting",
    "director of purchasing",
    "asst. cao",
    "director of",
    "and land use",
    "ofﬁce of the district attorney",
    "human resources",
    "probation",
    "public health",
    "all possible",
    "sdcera",
    "sherrif",
    "sherrif's",
    "sheriffs dept",
    "recorder/clerk",
    "employees retirement system",
    "treasurer",
    "atty.",
    "treasurer-tax",
    "county treasurer—tax collector",
    "planning",
    "pds",
    "assessor",
    "land use",
    "dpw",
    "members of planning commission",
    "directors of planning"
]

